apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    k8s-app: back-node
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: back-node
      app: api
  template:
    metadata:
      labels:
        k8s-app: back-node
        app: api
    spec:

      {{- with .Values.backAffinity }}
      tolerations:
        {{- toYaml .tolerations | nindent 6 }}
      affinity:
        {{- toYaml .affinity | nindent 8 }}
      {{- end }}

      containers:
      - name: api
        image: ryukenin/upylab_api_endpoint:latest
        env:
        - name: tempdir
          value: {{ .Values.tempdir }}
        - name: max_file_mb
          value: {{ .Values.max_file_mb | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /tmp/compilab/
          name: filestore

        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m


      volumes:
      - name: filestore
        persistentVolumeClaim:
          claimName: filestore-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000           # port: Port within the cluster where the service is available
      targetPort: 3000     # targetPort: Port on the pods where the service forwards traffic
      nodePort: 30000      # nodePort: Port exposed on each node for external access (if type is NodePort)
---
{{- if not .Values.deployFrontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000
{{- end }}
