apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-endpoint
  labels:
    app: api-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-endpoint
  template:
    metadata:
      labels:
        app: api-endpoint
    spec:
      runtimeClassName: gvisor  # run pod in gke sandbox

      containers:
      - name: api
        image: ryukenin/upylab-endpoint:latest
        env:
          - name: tempdir
            value: {{ .Values.tempdir }}
          - name: max_file_mb
            value: {{ .Values.max_file_mb | quote }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /tmp/compilab/
          name: filestore

        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m

      volumes:
      - name: filestore
        persistentVolumeClaim:
          claimName: filestore-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api-endpoint
  ports:
    - protocol: TCP
      port: 3000           # port: Port within the cluster where the service is available
      targetPort: 3000     # targetPort: Port on the pods where the service forwards traffic
      nodePort: 30000      # nodePort: Port exposed on each node for external access (if type is NodePort)
{{ if not .Values.deployFrontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000
{{ end }}
#---
#apiVersion: autoscaling.k8s.io/v1
#kind: VerticalPodAutoscaler
#metadata:
#  name: api-endpoint-vpa
#  namespace: default
#spec:
#  targetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: api-endpoint
#  updatePolicy:
#    updateMode: "Auto"
