apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    k8s-app: back-node
    app: celery-worker
spec:
  replicas: {{ .Values.replica }}

  selector:
    matchLabels:
      k8s-app: back-node
      app: celery-worker
  template:
    metadata:
      labels:
        k8s-app: back-node
        app: celery-worker
    spec:
      runtimeClassName: gvisor  # run pod in gke sandox

      {{- toYaml .Values.back-affinity | nindent 6 }}

      {{- if .Values.seccomp_profile.enabled }}
      initContainers:
        - name: upylab-seccomp
          image: ryukenin/upylab-seccomp:new
          volumeMounts:
            - mountPath: /var/lib/kubelet/seccomp/profiles
              name: data
      {{- end }}

      containers:
      - name: celery-worker
        image: ryukenin/upylab-celery-worker:{{ .Values.python_version }}
        imagePullPolicy: Always
        {{- if .Values.seccomp_profile.enabled }}
        securityContext:
          seccompProfile:
            type: Localhost
            localhostProfile: profiles/config.json
        {{- end }}

        resources:
          limits:
            memory: {{ .Values.memory_limits }}
            cpu: {{ .Values.cpu_limits }}
          requests:
            memory: {{ .Values.memory_requests }}
            cpu: {{ .Values.cpu_requests }}

        volumeMounts:
        - mountPath: /tmp/compilab/
          name: filestore
        {{- if .Values.seccomp_profile.enabled }}
        - mountPath: /var/lib/kubelet/seccomp/profiles
          name: data
        {{- end }}

      volumes:
      {{- if .Values.seccomp_profile.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: shared-pvc
      {{- end }}
      - name: filestore
        persistentVolumeClaim:
          claimName: filestore-pvc
