apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-upylab
  labels:
    k8s-app: api-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-upylab
      k8s-app: api-node
  template:
    metadata:
      labels:
        app: redis-upylab
        k8s-app: api-node
    spec:

      tolerations:
      - key: affinity-taint
        operator: Equal
        value: front-end
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: affinity-label
                operator: In
                values:
                - front-end

      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: 200Mi
            cpu: 150m
          limits:
            memory: 500Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: redis-upylab
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-upylab
