apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-upylab
  labels:
    k8s-app: api-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-upylab
      k8s-app: api-node
  template:
    metadata:
      labels:
        app: redis-upylab
        k8s-app: api-node
    spec:
      #affinity:
      #  podAntiAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #    - labelSelector:
      #        matchExpressions:
      #        - key: k8s-app
      #          operator: In
      #          values:
      #          - api-node
      #          - front-node
      #      topologyKey: "kubernetes.io/hostname"

      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: {{ .Values.memory }}
            cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: redis-upylab
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-upylab
