apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres:13.3
        envFrom:
        - configMapRef:
            name: db-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgresdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: upylab_db
  DATABASE_HOST: postgresdb
  DATABASE_PORT: "5432"
  # Django settings
  SECRET_KEY: "qj8nyxnmjo2(jz+1c5i$4)mp6kdmg-:&6_n*y9_8c#r^is1po)"
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  TIME_ZONE: 'Europe/Brussels'

  # Site configuration
  SITE_PROTOCOL: http
  SITE_DOMAIN: upylab2.ulb.ac.be
  SITE_EMAIL: upylab@ulb.be
  SITE_EMAIL_PASSWORD: <>

  # Prof signup restricted
  PROF_SIGNUP_RESTRICTED: "False"
  PROF_SIGNUP_RESTRICTED_CONTACT_NAME: "UpyLaB"
  PROF_SIGNUP_RESTRICTED_CONTACT_EMAIL: upylab@ulb.be

  # Backend API connection
  BKEND_API_SECRET_KEY: helloworld
  BKEND_API_ADDR_TESTSOLUTION: 35.246.162.144:80/test_solution
  BKEND_API_ADDR_TESTEXERCISE: 35.246.162.144:80/test_exercice
