
# worker configuration
python_version: "3.12-slim"
cpu_limits: 500m
memory_limits: 500Mi
cpu_requests: 500m
memory_requests : 256Mi
replica : 1

# seccompp
seccomp_profile :
  enabled: false

restrict_system_call:
  - exit
  - open
  - read

# backend-endpoint
tempdir : "/tmp/compilab/"
max_file_mb : 1


# frontend
deployFrontend :
  enabled: true


frontAffinity :
  tolerations:
  - key: affinity-taint
    operator: Equal
    value: front-end
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: affinity-label
            operator: In
            values:
            - front-end

backAffinity :
  tolerations:
  - key: affinity-taint
    operator: Equal
    value: back-end
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: affinity-label
            operator: In
            values:
            - back-end

memory: 512Mi

deploySSL :
  enabled: true

timezone: 'Europe/Brussels'

#site_domain: upylab2.ulb.ac.be
site_domain: upylab.duckdns.org
site_protocol: https
site_email: nymano@s19.be
site_email_password: "<>"
site_email_host: smtp.gmail.com
site_email_port: "587"

allowed_hosts: '*'
