
# worker configuration
python_version: "3.12-slim"
cpu_limits: 500m
memory_limits: 512Mi
cpu_requests: 300m
memory_requests : 256Mi
replica : 3

# seccompp
seccomp_profile :
  enabled: false

restrict_system_call:
  - exit
  - open
  - read

# backend-endpoint
tempdir : "/tmp/compilab/"
max_file_mb : 1

dev_mode :
  enabled: true

# frontend
deployFrontend :
  enabled: true

deploySSL :
  enabled: true

timezone: 'Europe/Brussels'

#site_domain: upylab2.ulb.ac.be
site_domain: upylab.duckdns.org
site_protocol: https
allowed_hosts: '*'

# mail settings
site_email: upylab@ulb.be
site_email_password: Y4u%y^#Ez88nUp
site_email_host: smtp.office365.com
site_email_port: "587"

