
# worker configuration
python_version: "3.10"
cpu_limits: 500m
memory_limits: 512Mi
cpu_requests: 200m
memory_requests : 256Mi
replica : 2

restrict_system_call:
  - exit
  - open
  - read

# backend-endpoint
tempdir : /tmp/compilab/
max_file_mb : 1

deployUpylab2 : True
