
# -- worker configuration --
python_version: "3.12"
cpu_limits: 1000m
memory_limits: 1024Mi
cpu_requests: 800m
memory_requests : 512Mi
replica : 1

# -- worker env --
# set the timeout in seconds for the execution of the code
TIMEOUT : "1"
UNSAFE_MODULES : "socket,ctypes,shutil"


# pod affinity
frontAffinity :
  tolerations:
  - key: affinity-taint
    operator: Equal
    value: front-end
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - front-end

backAffinity :
  tolerations:
  - key: affinity-taint
    operator: Equal
    value: back-end
    effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - back-end


# seccomp
seccomp_profile:
  enabled: false
restrict_system_call:
  - exit
  - open
  - read

# -- backend-endpoint --
tempdir : "/tmp/compilab"
# set the maximum file size in MB that can be included in the test
max_file_mb : "5"

# if dev_mode is enabled, the DEBUG mode is activated in django
# and the SSL certificate can be self-signed (named my-certificate)
dev_mode :
  enabled: false

# if deployFrontend is enabled, the django application is deployed and exposed through nginx
deployFrontend:
  enabled: true

timezone: "Europe/Brussels"
# site_domain: "upylab2.ulb.ac.be"
site_domain: "your-domain.com"
