
# worker configuration
python_version: "3.10"
cpu_limits: 500m
memory_limits: 512Mi
cpu_requests: 200m
memory_requests : 256Mi
replica : 1

# seccompp
seccomp_profile :
  enabled: false

restrict_system_call:
  - exit
  - open
  - read

# backend-endpoint
tempdir : "/tmp/compilab/"
max_file_mb : 1


# frontend
deployFrontend :
  enabled: true

memory: 200Mi

deploySSL :
  enabled: true

timezone: 'Europe/Brussels'

#site_domain: upylab2.ulb.ac.be
site_domain: upylab.duckdns.org
site_protocol: https
site_email: nymano@s19.be
site_email_password: "<>"
site_email_host: smtp.gmail.com
site_email_port: "587"

allowed_hosts: '*'
