
{{ if .Values.deployFrontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
  POSTGRES_DB: upylab_db
  DATABASE_HOST: postgresdb
  DATABASE_PORT: "5432"
  # Django settings
  SECRET_KEY: "qj8nyxnmjo2(jz+1c5i$4)mp6kdmg-:&6_n*y9_8c#r^is1po)"
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  TIME_ZONE: {{ .Values.timezone }}

  # Site configuration
  SITE_PROTOCOL: {{ .Values.site_protocol }}
  SITE_DOMAIN: {{ .Values.site_domain }}
  SITE_EMAIL: {{ .Values.site_email }}
  SITE_EMAIL_PASSWORD: {{ .Values.site_email_password }}
  SITE_EMAIL_HOST: {{ .Values.site_email_host }}
  SITE_EMAIL_PORT: {{ .Values.site_email_port | quote }}

  # Prof signup restricted
  PROF_SIGNUP_RESTRICTED: "False"
  PROF_SIGNUP_RESTRICTED_CONTACT_NAME: "UpyLaB"
  PROF_SIGNUP_RESTRICTED_CONTACT_EMAIL: upylab@ulb.be

  # Backend API connection
  BKEND_API_SECRET_KEY: helloworld
  BKEND_API_ADDR_TESTSOLUTION: http://api-service.default.svc.cluster.local:3000/test_solution
  BKEND_API_ADDR_TESTEXERCISE: http://api-service.default.svc.cluster.local:3000/test_exercice
{{ end }}
