{{ if .Values.deployFrontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:

      containers:
      - name: postgresdb
        image: postgres:13.3
        #envFrom:
        #- configMapRef:
        #    name: db-config
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: DATABASE_PORT
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: POSTGRES_PASSWORD

        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        resources:
          requests:
            memory: 312Mi
            cpu: 250m
          limits:
            memory: 600Mi
            cpu: 500m
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgresdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: postgresdb-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgresdb
  updatePolicy:
    updateMode: "Auto"
{{ end }}
