{{ if .Values.deployFrontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  labels:
    k8s-app: api-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:

      tolerations:
      - key: affinity-taint
        operator: Equal
        value: front-end
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: affinity-label
                operator: In
                values:
                - front-end

      containers:
      - name: postgresdb
        image: postgres:13.3
        envFrom:
        - configMapRef:
            name: db-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgresdata
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        resources:
          requests:
            memory: 1032Mi
            cpu: 500m
          limits:
            memory: 2064Mi
            cpu: 1000m
      volumes:
      - name: postgresdata
        persistentVolumeClaim:
          claimName: postgresdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgresdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdata-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{ end }}
