apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    #kubernetes.io/pre-shared-cert: "staging-google-managed-ssl"
    ingress.kubernetes.io/ssl-redirect: "true"
    {{ if .Values.dev_mode.enabled }}
    networking.gke.io/managed-certificates: my-certificate
    {{ else }}
    kubernetes.io/spec.ingressClassName: "gce"
    networking.gke.io/managed-certificates: upylab-certificate
    {{ end }}
    kubernetes.io/ingress.global-static-ip-name: "static-ip"
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_set_header X-Original-Protocol https;
spec:
  rules:
    - host: {{ .Values.site_domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
  tls:
  - hosts:
    - upylab.duckdns.org
    secretName: upylab-certificate
