{{ if .Values.deployFrontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ryukenin/upylab-nginx:latest
        imagePullPolicy: Always
        env:
        - name: SITE_DOMAIN
          value: {{ .Values.site_domain }}
        - name: NGINX_ENVSUBST_OUTPUT_DIR
          value: /etc/nginx/conf.d
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: staticroot
          mountPath: /app/web/static_root
        - name: mediaroot
          mountPath: /app/web/media_root
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
      volumes:
      - name: staticroot
        persistentVolumeClaim:
          claimName: staticroot-pvc
      - name: mediaroot
        persistentVolumeClaim:
          claimName: mediaroot-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTPS","http":"HTTP"}'
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: nginx
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nginx-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  updatePolicy:
    updateMode: "Auto"
{{ end }}
