{{ if .Values.deployFrontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-upylab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-upylab
  template:
    metadata:
      labels:
        app: redis-upylab
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: {{ .Values.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-upylab
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-upylab
{{ end }}
